//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public class GlobalWork
{
    static protected GlobalWork m_instance = null;
    static protected bool m_safeFlag = false;

    /// <summary>
    /// return the singleton of this class 
    /// </summary>
	static public GlobalWork SharedInstance
	{
        get
        {
            if( m_instance == null )
            {
                m_safeFlag = true;
                m_instance = new GlobalWork();
                m_safeFlag = false;
            }

            return m_instance;
        }
	}

    protected int m_score;

    /// <summary>
    /// constructor 
    /// </summary>
	public GlobalWork ()
	{
        if( m_safeFlag == false )
        {
            Debug.LogError("[GlobalWork]: singleton can not be create directly.");
        }

        m_score = 0;
	}

    /// <summary>
    /// getter && setter of the score 
    /// </summary>
    public int SCORE
    {
        get
        {
            return m_score;
        }
        set
        {
            m_score = value;
        }
    }

}
